name: active_wrapper
version: 0.4.7
authors:
  - Winton Welsh
email: mail@wintoni.us
homepage: http://github.com/winton/active_wrapper
summary: Wraps ActiveRecord and Logger for use in non-Rails environments
description: Wraps ActiveRecord and Logger for use in non-Rails environments
dependencies:
  - default:
    - activerecord
  - ar2:
    - activerecord
development_dependencies:
  - rake
  - rspec